# Generated by Django 4.2.11 on 2026-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('normal', 'User')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('normal', 'User')], default='normal', max_length=20),
        ),
    ]
