# Generated by Django 4.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(
                choices=[
                    ('registration', 'Registration'),
                    ('password_reset', 'Password reset'),
                ],
                default='registration',
                max_length=30,
            ),
        ),
    ]
