# Generated by Django 4.2.11 on 2026-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills list.')),
                ('portfolio_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
