# Generated by Django 5.2.5 on 2026-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_benefits_job_benefits_en_job_benefits_nl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English')], default='nl', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
