# Generated by Django 5.2.5 on 2026-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogcategory_name_en_blogcategory_name_nl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('logo_url', models.URLField(blank=True, help_text='Optional URL to a logo image hosted elsewhere')),
                ('website', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=180)),
                ('author_role', models.CharField(blank=True, help_text='e.g. Operations Manager, Acme Corp', max_length=180)),
                ('author_role_en', models.CharField(blank=True, default='', max_length=180)),
                ('author_role_nl', models.CharField(blank=True, default='', max_length=180)),
                ('message_en', models.TextField(blank=True, default='')),
                ('message_nl', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='', help_text='Legacy single-language fallback')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
