# Generated by Django 4.2.11 on 2026-06-03 04:21

import apps.content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_partner_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tif', 'tiff', 'ico', 'svg']), apps.content.models._validate_partner_logo_file]),
        ),
    ]
