# Generated by Django 5.2.5 on 2026-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='application',
            name='other_document',
            field=models.FileField(blank=True, help_text='Aadhar card, PAN card, or other identity document', null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/resumes/'),
        ),
    ]
