# Generated by Django 5.2.5 on 2026-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_resume_and_other_document_to_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='other_document',
        ),
        migrations.AddField(
            model_name='application',
            name='aadhaar_card',
            field=models.FileField(blank=True, help_text='Aadhaar Card (mandatory)', null=True, upload_to='applications/aadhaar/'),
        ),
        migrations.AddField(
            model_name='application',
            name='pan_card',
            field=models.FileField(blank=True, help_text='PAN Card (mandatory)', null=True, upload_to='applications/pan/'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, help_text='Passport (mandatory)', null=True, upload_to='applications/passport/'),
        ),
    ]
