# Generated by Django 4.2.11 on 2026-05-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_other_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='applications/resumes/'),
        ),
    ]
